---
title: "Final_Belle"
output: flexdashboard::flex_dashboard
runtime: shiny
---

```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
library(ggmosaic)
library(shiny)
library(ggiraph)
library(bslib)
library(rlang)
library(flexdashboard)
library(dbplyr)
```

```{r, echo = FALSE}
songs = read_rds("songs.csv")
genres = read_rds("genres.csv")
artists = read_rds("artists.csv")

songs2 <- 
  songs |>
  mutate(duration_m = duration_ms/60000)

```


Tonality For Each Genre
==========================

Inputs {.sidebar}
-------------------------

Genres

```{r, echo=FALSE}
  inputPanel(
    checkboxGroupInput("genre_check2", "Select Genres:",
                       choices = c("All", unique(as.character(songs$genre))),                         
                       selected = "All")
  )

```

Row
-------------------------------------

```{r, echo=FALSE}
renderPlot({
    filtered_songs <- if("All" %in% input$genre_check2) {
      songs
    } else {
      songs %>% filter(genre %in% input$genre_check2)
    }

    ggplot(filtered_songs) + 
      geom_mosaic(aes(x = product(genre), fill = mode_name)) +
      labs(x = "Genre",
           title = "Mode For Each Genre",
           fill = "Mode") +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1))
  })

```

Row
-------------------------------------

```{r, echo=FALSE}
renderPlot({
    filtered_songs <- if("All" %in% input$genre_check2) {
      songs
    } else {
      songs %>% filter(genre %in% input$genre_check2)
    }

     
    ggplot(filtered_songs) + 
      geom_mosaic(aes(x = product(genre), fill = key_name)) +
      labs(x = "Genre",
           title = "Key For Each Genre",
           fill = "Key") +
      theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust=1)) 
  })
```


Tonality For Top Artists
==========================

```{r, echo = FALSE}
inputPanel(
 selectInput("genre4", label = "Genre:", 
             choices = c("R&B" = "R&B",
                         "Christian" = "christian",
                         "Country" = "country",
                         "EDM" = "edm",
                         "Hip-Hop" = "hip-hop",
                         "Indie" = "indie",
                         "Latin" = "latin",
                         "Pop" = "pop",
                         "Rap" = "rap",
                         "Rock" = "rock"))
)
```

Column {data-width = 200}
-------------------------


```{r, echo = FALSE}
renderPlot({
  songs2 %>%
    filter(genre == input$genre4)|>
    
  ggplot() +
    geom_mosaic(aes(x = product(name), fill = key_name)) +
    labs(x = "Singer Name", y = "Key of Songs", color = "Artist Name") + 
    theme_classic() + 
    scale_color_calc()
})
```


Column {data-width = 200}
-------------------------------------


```{r, echo = FALSE}
renderPlot({
  songs2 %>%
    filter(genre == input$genre4)|>
    
  ggplot() +
    geom_mosaic(aes(x = product(name), fill = mode_name)) +
    labs(x = "Singer Name", y = "Mode of Song", color = "Artist Name") + 
    theme_classic() + 
    scale_color_calc()
})
```


