---
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r}
library(tidyverse)
library(stringr)
library(dplyr)
library(rvest)
library(httr)
library(spotifyr)
library(ggplot2)
```


```{r}
songs = read_rds("songs.csv")

indie <- get_genre_artists("indie", limit = 50)
country <- get_genre_artists("country", limit = 50)
rock <- get_genre_artists("rock", limit = 50)
pop <- get_genre_artists("pop", limit = 50)
rap <- get_genre_artists("rap", limit = 50)
edm <- get_genre_artists("edm", limit = 50)
latin <- get_genre_artists("latin", limit = 50)
christian <- get_genre_artists("christian", limit = 50)
hip_hop <- get_genre_artists("hip-hop", limit = 50)
r_b <- get_genre_artists("R&B", limit = 50)

genres <- indie |>
  full_join(country) |>
  full_join(rock) |>
  full_join(pop) |>
  full_join(rap) |>
  full_join(edm) |>
  full_join(latin) |>
  full_join(christian) |>
  full_join(hip_hop) |>
  full_join(r_b) |>
  distinct(name, .keep_all = TRUE)
```

```{r}
genres |>
  ggplot(aes(x = genre, y = followers.total)) +
  geom_boxplot()

genres |>
  ggplot(aes(x = genre, y = popularity)) +
  geom_boxplot()
```

```{r}
songs |>
  ggplot(aes(x = album_release_year, y = tempo, color = genre)) +
  geom_point() + 
  facet_wrap(~genre)

songs |>
  filter(genre == "indie") |>
  ggplot(aes(x = album_release_year, y = tempo, color = genre)) +
  geom_point() + 
  geom_smooth(method = "lm", se = F)

songs |>
  ggplot(aes(x = popularity, y = energy, color = genre)) +
  geom_point()

songs |>
  ggplot(aes(x = duration_ms, y = popularity, color = genre)) +
  geom_point()

songs |>
  group_by(album_name) |>
  mutate(num_songsalbum = n()) |>
  ggplot(aes(x = popularity, y = num_songsalbum, color = genre)) +
  geom_violin()

songs |>
  ggplot(aes(x = danceability, color = genre)) +
  geom_density()

songs |>
  group_by(album_name) |>
  mutate(num_songsalbum = n()) |>
  ggplot(aes(x = album_release_year, y = num_songsalbum, color = genre)) +
  geom_point()

songs |>
  filter(genre == "country") |>
  group_by(album_name) |>
  mutate(num_songsalbum = n()) |>
  ggplot(aes(x = album_release_year, y = num_songsalbum, color = genre)) +
  geom_point() +
  geom_smooth(se = F)

songs |>
  filter(genre == "hip-hop") |>
  ggplot(aes(x = album_release_year, y = duration_ms)) +
  geom_point()
```

