---
title: "Project"
output: flexdashboard::flex_dashboard
runtime: shiny
---


```{r global, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggthemes)
library(viridis)
```

```{r, echo = FALSE}
songs = read_rds("songs.csv")
genres = read_rds("genres.csv")
artists = read_rds("artists.csv")

songs2 <- 
  songs |>
  mutate(duration_m = duration_ms/60000)
```

1
==========================

Column {data-width = 200}
-------------------------

```{r, echo=FALSE}
inputPanel(
 selectInput("y", label = "y-axis variable:",
    choices = c("Danceability" = "danceability",
                "Energy" = "energy",
                "Loudness" = "loudness",
                "Speechiness" = "speechiness", 
                "Acousticness" = "acousticness", 
                "Instrumentalness" = "instrumentalness",
                "Liveness" = "liveness",
                "Valence" = "valence",
                "Tempo" = "tempo")),
 selectInput("genre", label = "Genre 1:", 
             choices = c("R&B" = "R&B",
                         "Christian" = "christian",
                         "Country" = "country",
                         "EDM" = "edm",
                         "Hip-Hop" = "hip-hop",
                         "Indie" = "indie",
                         "Latin" = "latin",
                         "Pop" = "pop",
                         "Rap" = "rap",
                         "Rock" = "rock")),
 selectInput("genre0", label = "Genre 2:", 
             choices = c("R&B" = "R&B",
                         "Christian" = "christian",
                         "Country" = "country",
                         "EDM" = "edm",
                         "Hip-Hop" = "hip-hop",
                         "Indie" = "indie",
                         "Latin" = "latin",
                         "Pop" = "pop",
                         "Rap" = "rap",
                         "Rock" = "rock"))
)

renderPlot({
  filtered_songs <- songs %>%
    filter(genre %in% c(input$genre, input$genre0))
  
  ggplot(filtered_songs, aes(y = .data[[input$y]], x = album_release_year, color = genre)) + 
    geom_point() + 
    geom_smooth(method = "lm", se = F) + labs(x = "Album Release Year", color = "Genre") + theme_classic() + scale_color_calc()
})
```

Column {data-width = 200}
-------------------------

```{r, echo = FALSE}
inputPanel(
  selectInput("x2", label = "x-axis variable:",
    choices = c("Danceability" = "danceability",
                "Energy" = "energy",
                "Loudness" = "loudness",
                "Speechiness" = "speechiness", 
                "Acousticness" = "acousticness", 
                "Instrumentalness" = "instrumentalness",
                "Liveness" = "liveness",
                "Valence" = "valence",
                "Tempo" = "tempo")),
 selectInput("genre2", label = "Genre 1:", 
             choices = c("R&B" = "R&B",
                         "Christian" = "christian",
                         "Country" = "country",
                         "EDM" = "edm",
                         "Hip-Hop" = "hip-hop",
                         "Indie" = "indie",
                         "Latin" = "latin",
                         "Pop" = "pop",
                         "Rap" = "rap",
                         "Rock" = "rock")),
 selectInput("genre02", label = "Genre 2:", 
             choices = c("R&B" = "R&B",
                         "Christian" = "christian",
                         "Country" = "country",
                         "EDM" = "edm",
                         "Hip-Hop" = "hip-hop",
                         "Indie" = "indie",
                         "Latin" = "latin",
                         "Pop" = "pop",
                         "Rap" = "rap",
                         "Rock" = "rock"))
)

renderPlot({
  filtered_songs <- songs %>%
    filter(genre %in% c(input$genre2, input$genre02))
  
  ggplot(filtered_songs, aes(x = .data[[input$x2]], fill = genre)) + 
    geom_density(alpha = 0.5) + labs(fill = "Genre") + theme_classic() + scale_fill_calc()
})
```

2
==========================

<center>

```{r, echo = FALSE}
inputPanel(
 selectInput("genre3", label = "Genre:", 
             choices = c("R&B" = "R&B",
                         "Christian" = "christian",
                         "Country" = "country",
                         "EDM" = "edm",
                         "Hip-Hop" = "hip-hop",
                         "Indie" = "indie",
                         "Latin" = "latin",
                         "Pop" = "pop",
                         "Rap" = "rap",
                         "Rock" = "rock"))
)
```

Column 
-------------------------

```{r, echo = FALSE}
renderPlot({
  songs2 |>
    filter(genre == input$genre3) |>
    group_by(album_name) |>
  mutate(num_songsalbum = n()) |>
  ggplot(aes(y = num_songsalbum, x = album_release_year, color = name)) + 
    geom_point() + geom_smooth(method = "lm", se = FALSE) + labs(x = "Album Release Year", color = "Artist Name", y = "Number of Songs per Album")+ theme_classic() + scale_color_calc()
})

renderPlot({
  filtered_songs <- songs %>%
    filter(genre == input$genre3) |>
   group_by(album_name) |>
  mutate(num_songsalbum = n()) 
  
  ggplot(filtered_songs, aes(x = popularity, y = num_songsalbum, color = name)) + 
    geom_boxplot() + labs(x = "Popularity", y = "Number of Songs per Album") + theme_classic() + scale_color_calc()
})
```

3
==========================

Inputs {.sidebar}
-------------------------

```{r, echo=FALSE}
inputPanel(
  checkboxGroupInput("genre_check", "Select Genres:",
                     choices = c("R&B", "Christian", "Country", "EDM", "Hip-Hop", "Indie", "Latin", "Pop", "Rap", "Rock"),
                     selected = NULL),
  selectInput("x5", label = "x-axis variable:",
    choices = c("Popularity" = "popularity",
                "Followers" = "followers.total")),
 selectInput("y5", label = "y-axis variable:",
    choices = c("Danceability" = "danceability",
                "Energy" = "energy",
                "Loudness" = "loudness",
                "Speechiness" = "speechiness", 
                "Acousticness" = "acousticness", 
                "Instrumentalness" = "instrumentalness",
                "Liveness" = "liveness",
                "Valence" = "valence",
                "Tempo" = "tempo"))
)
```

Column 
-------------------------

```{r, echo = FALSE}
#renderPlot({
  #filtered_songs <- songs %>%
    #filter(genre %in% input$genre_check)
  #ggplot(filtered_songs, aes(y = .data[[input$y5]], x = .data[[input$x5]])) + 
 #   geom_violin()
#})

renderPlot({
  songs |>
    filter(genre %in% input$genre_check) |>
    ggplot(aes(x = .data[[input$x5]], y = .data[[input$y5]])) +
    geom_point()})

```


